### PR TITLE
Background subtraction and updates to snp file reading

### PR DESCRIPTION
**Pull request by nmaterise**
Updates background subtraction in the resfit module with changes made to the interface of the `background_removal()` function. The new interface is symmetric in the background and original data formats as `VNASweep` objects. New plotting functions take output file formats as inputs, as well as data labels in the legends, axes labels, and improved scaling of the axes ticks, labels, and legend text fonts.

### CODE REVIEW

**Comment by nmaterise** [comment]
There might be overlapping work in this pull request with @mullinska in his pull request #89.

**Comment by nmaterise** [comment]
Merge conflicts with #89 are now resolved. Ready for review.

**Comment by crmcrae** [comment]
There seem to be a lot of commits in this pull request, including one that uploads some datasets. Is that intentional?

**Comment by nmaterise** [comment]
> There seem to be a lot of commits in this pull request, including one that uploads some datasets. Is that intentional?

I think those are older commits that I tried to squash in my previous pull request #88.
I will see if I can resolve the issue from my fork, not sure why the branch I pushed had those other commits.

**Comment by nmaterise** [comment]
> > There seem to be a lot of commits in this pull request, including one that uploads some datasets. Is that intentional?
> 
> I think those are older commits that I tried to squash in my previous pull request #88.
> I will see if I can resolve the issue from my fork, not sure why the branch I pushed had those other commits.

I think the above commits should resolve the previous issues.

**Pull request closed without merging**
